//
// Auto-generated by dnne-gen
//
// .NET Assembly: managed
//

//
// Declare exported functions
//
#ifndef __DNNE_GENERATED_HEADER_MANAGED__
#define __DNNE_GENERATED_HEADER_MANAGED__

#include <stddef.h>
#include <stdint.h>
#ifdef DNNE_COMPILE_AS_SOURCE
    #include <dnne.h>
#else
    // When used as a header file, the assumption is
    // dnne.h will be next to this file.
    #include "dnne.h"
#endif // !DNNE_COMPILE_AS_SOURCE

// Computed from Program.CallMe
DNNE_EXTERN_C DNNE_API void DNNE_CALLTYPE CallMe(void);

#endif // __DNNE_GENERATED_HEADER_MANAGED__

//
// Define exported functions
//
#ifdef DNNE_COMPILE_AS_SOURCE

#ifdef DNNE_WINDOWS
    #ifdef _WCHAR_T_DEFINED
        typedef wchar_t char_t;
    #else
        typedef unsigned short char_t;
    #endif
#else
    typedef char char_t;
#endif

//
// Forward declarations
//

extern void* get_callable_managed_function(
    const char_t* dotnet_type,
    const char_t* dotnet_type_method,
    const char_t* dotnet_delegate_type);

extern void* get_fast_callable_managed_function(
    const char_t* dotnet_type,
    const char_t* dotnet_type_method);

//
// String constants
//

#ifdef DNNE_TARGET_NET_FRAMEWORK
    static const char_t* t1_name = DNNE_STR("Program");
#else
    static const char_t* t1_name = DNNE_STR("Program, managed");
#endif // !DNNE_TARGET_NET_FRAMEWORK


//
// Exports
//

// Computed from Program.CallMe
static void (DNNE_CALLTYPE* CallMe_ptr)(void);
DNNE_EXTERN_C DNNE_API void DNNE_CALLTYPE CallMe(void)
{
    if (CallMe_ptr == NULL)
    {
        const char_t* methodName = DNNE_STR("CallMe");
        CallMe_ptr = (void(DNNE_CALLTYPE*)(void))get_fast_callable_managed_function(t1_name, methodName);
    }
    CallMe_ptr();
}

#endif // DNNE_COMPILE_AS_SOURCE
